DDu-Du-DDu-Du/back-end

config/checkstyle/checkstyle.xml, config/checkstyle/suppressions.xml
Resolves #9 
* 커스텀 CheckStyle 적용
* Checkstyle 설정 파일 생성
* Suppressions 파일 생성
=> CheckStyle 적용

.github/workflows/ci-pipeline.yaml
Resolves #23 
* CI 시 Gradle 캐싱 적용
* Jacoco 테스트 결과 출력
=> CI 파이프라인 개선

scripts/local/Dockerfile
=> Dockerfile에 DB 타임존 서울로 추가

.github/workflows/ci-pipeline.yaml, build.gradle, config/checkstyle/checkstyle.xml, src/test/java/com/ddudu/DduduApplicationTests.java
Resolves #28 
* 지난번 애먹었던 checkstyle 이슈를 찾아서 고쳤습니다!
* 메서드 명과 타입 명 한글 허용
* Checkstyle 빌드 태스크 추가
* CI에 Checkstyle 리포트 출력 step 추가
* 아쉽게도 PR에 추가해주는 actions는 없어서 Checks에 작성했습니다
=> 체크스타일 메서드 명과 타입 명 한글 허용

src/main/java/com/ddudu/goal/domain/Goal.java, src/main/java/com/ddudu/goal/repository/GoalRepository.java, src/main/java/com/ddudu/todo/controller/TodoController.java, src/main/java/com/ddudu/todo/domain/Todo.java, src/main/java/com/ddudu/todo/dto/response/TodoResponse.java, src/main/java/com/ddudu/todo/repository/TodoRepository.java, src/main/java/com/ddudu/todo/service/TodoService.java, src/test/java/com/ddudu/todo/controller/TodoControllerTest.java, src/test/java/com/ddudu/todo/service/TodoServiceTest.java
Resolves #15
- Todo에 Getter 어노테이션 추가
- Repository, Service, Controller 코드 작성
- Service, Controller 테스트 코드 작성
<br/>
너무 오래 걸렸네요 😢 다음 PR부터 속도를 높여보겠습니다..!
=> 할 일 1개(단일) 조회 기능 구현

src/main/java/com/ddudu/user/domain/User.java, src/main/java/com/ddudu/user/dto/request/SignUpRequest.java, src/main/java/com/ddudu/user/service/UserService.java, src/main/resources/db/migration/V1__schema.sql, src/test/java/com/ddudu/user/controller/UserControllerTest.java, src/test/java/com/ddudu/user/domain/UserTest.java, src/test/java/com/ddudu/user/service/UserServiceTest.java
Resolves #30 
* 유저 스키마 및 엔티티에 자기소개 추가
* 자기소개 길이 검증
* 회원가입 시 자기소개 선택적으로 기입
=> 회원가입 시 자기소개 추가

src/main/java/com/ddudu/todo/controller/TodoController.java, src/main/java/com/ddudu/todo/domain/Todo.java, src/main/java/com/ddudu/todo/dto/response/TodoInfo.java, src/main/java/com/ddudu/todo/service/TodoService.java, src/test/java/com/ddudu/todo/controller/TodoControllerTest.java, src/test/java/com/ddudu/todo/service/TodoServiceTest.java
Resolves #37 
- TodoInfo status 타입 변경 (String -> TodoStatus)
- ControllerTest 메서드 이름에 HTTP method 추가
- 할 일 상태 변경 기능 구현
- 테스트 코드 작성
=> 할 일 상태 변경 기능 구현

src/main/java/com/ddudu/common/BaseEntity.java, src/main/java/com/ddudu/common/BaseTimeEntity.java, src/main/java/com/ddudu/goal/domain/Goal.java, src/main/java/com/ddudu/todo/domain/Todo.java, src/main/java/com/ddudu/user/domain/User.java
=> BaseTimeEntity 생성 및 적용

src/main/java/com/ddudu/goal/domain/Goal.java, src/main/java/com/ddudu/todo/controller/TodoController.java, src/main/java/com/ddudu/todo/domain/Todo.java, src/main/java/com/ddudu/todo/dto/request/UpdateTodoRequest.java, src/main/java/com/ddudu/todo/service/TodoService.java, src/test/java/com/ddudu/todo/controller/TodoControllerTest.java, src/test/java/com/ddudu/todo/service/TodoServiceTest.java, src/test/java/com/ddudu/user/domain/UserTest.java
Resolves #88 
- [할 일 수정 API 문서 작성](https://www.notion.so/backend-devcourse/1a508bc28ff84a4db087809c1fe8ab6d?pvs=4)
- 할 일 수정 기능 구현
- 할 일 수정 기능 테스트 코드 작성
=> 할 일 수정 기능 구현

README.md
=> docs: README 파일 생성

README.md
- 오타 수정
- 기술 스택 순서 변경
다음부턴 readme 브랜치 따서 할게요.. 죄송합니당..!
=> docs: README.md 오타 수정

src/main/java/com/ddudu/goal/controller/GoalController.java, src/main/java/com/ddudu/goal/service/GoalService.java, src/test/java/com/ddudu/auth/service/AuthServiceTest.java, src/test/java/com/ddudu/common/resolver/LoginUserArgumentResolverTest.java, src/test/java/com/ddudu/goal/controller/GoalControllerTest.java, src/test/java/com/ddudu/goal/service/GoalServiceTest.java
=> 목표 전체적인 리팩토링

.github/workflows/cd-dev.yaml, .github/workflows/cd-pipeline.yaml, .github/workflows/ci-pipeline.yaml, Dockerfile
* #124 
* application yaml 분리
* CD 파이프라인
* 일단 ECR에 이미지 하나만 푸쉬하고 다음 작업 진행할게요
=> CD 파이프라인 부분 완성

.github/workflows/cd-dev.yaml, .github/workflows/cd-pipeline.yaml, src/main/java/com/ddudu/application/domain/user/dto/MeResponse.java, src/main/java/com/ddudu/application/domain/user/exception/UserErrorCode.java, src/main/java/com/ddudu/application/port/in/user/GetMyInfoUseCase.java, src/main/java/com/ddudu/application/port/out/user/UserLoaderPort.java, src/main/java/com/ddudu/application/service/auth/TokenRefreshService.java, src/main/java/com/ddudu/application/service/goal/CreateGoalService.java, src/main/java/com/ddudu/application/service/goal/RetrieveAllGoalsService.java, src/main/java/com/ddudu/application/service/user/GetMyInfoService.java, src/main/java/com/ddudu/infrastructure/persistence/adapter/UserPersistenceAdapter.java, src/main/java/com/ddudu/presentation/api/annotation/Login.java, src/main/java/com/ddudu/presentation/api/config/SwaggerConfig.java, src/main/java/com/ddudu/presentation/api/controller/AuthController.java, src/main/java/com/ddudu/presentation/api/controller/GoalController.java, src/main/java/com/ddudu/presentation/api/controller/UserController.java, src/test/java/com/ddudu/application/domain/goal/domain/GoalTest.java, src/test/java/com/ddudu/application/service/user/GetMyInfoServiceTest.java
* Resolves #140 
* 간단해서 별건 없습니다
* 테스트 조건 수정
* 50~100자 -> 51~100자
* 스웨거 기본 보안 설정
* 로그인 파라미터에 히든 파라미터 추가
=> 내 정보 불러오기 구현

.github/workflows/cd-pipeline.yaml
=> 토큰 수명 축소 및 퍼블릭 ECR로 변경

src/main/java/com/ddudu/application/domain/ddudu/dto/request/MoveDateRequest.java, src/main/java/com/ddudu/presentation/api/controller/DduduController.java, src/main/java/com/ddudu/presentation/api/doc/DduduControllerDoc.java
* #158 
* 소통을 위한 스웨거 업데이트만 선배포입니다.
=> 뚜두 미루기, 오늘하기용 날짜 변경 API 문서

src/main/java/com/ddudu/application/domain/ddudu/dto/request/RepeatAnotherDayRequest.java, src/main/java/com/ddudu/application/domain/ddudu/dto/response/RepeatAnotherDayResponse.java, src/main/java/com/ddudu/presentation/api/controller/DduduController.java, src/main/java/com/ddudu/presentation/api/doc/DduduControllerDoc.java
=> 뚜두 다른 날 반복하기 문서 추가

src/main/java/com/ddudu/application/domain/ddudu/domain/Ddudu.java, src/main/java/com/ddudu/application/domain/ddudu/domain/enums/DduduStatus.java, src/main/java/com/ddudu/application/domain/ddudu/dto/request/MoveDateRequest.java, src/main/java/com/ddudu/application/domain/ddudu/exception/DduduErrorCode.java, src/main/java/com/ddudu/application/port/in/ddudu/MoveDateUseCase.java, src/main/java/com/ddudu/application/port/out/ddudu/DduduUpdatePort.java, src/main/java/com/ddudu/application/service/ddudu/MoveDateService.java, src/main/java/com/ddudu/application/service/ddudu/PeriodSetupService.java, src/main/java/com/ddudu/infrastructure/persistence/adapter/DduduPersistenceAdapter.java, src/main/java/com/ddudu/infrastructure/persistence/entity/DduduEntity.java, src/main/java/com/ddudu/presentation/api/controller/DduduController.java, src/main/java/com/ddudu/presentation/api/doc/DduduControllerDoc.java, src/test/java/com/ddudu/application/domain/ddudu/domain/DduduTest.java, src/test/java/com/ddudu/application/service/ddudu/MoveDateServiceTest.java, src/test/java/com/ddudu/fixture/DduduFixture.java
* Resolves #158 
* 기존 포트 용도 확장
* PeriodSetup -> DduduUpdate
* 뚜두 마이그레이션 시 누락된 변경 추가
* 날짜 변경 비즈니스 로직 구현 및 테스트 작성
=> 뚜두 날짜 변경 구현

src/main/java/com/ddudu/presentation/api/config/WebSecurityConfig.java
=> fix: CSRF 문제 해결

src/main/java/com/ddudu/application/dto/ddudu/request/CreateDduduRequest.java
Resolves #210 
LocalDate 타입에 @NotBlank 유효성 검사를 하는 오류 수정
=> 🚨 뚜두 생성 시 발생하는 오류 수정

src/main/java/com/ddudu/infrastructure/persistence/converter/RepeatPatternConverter.java
=> RepeatPattern 객체를 직렬화하지 못하는 오류 해결

src/main/java/com/ddudu/application/port/out/repeat_ddudu/DeleteRepeatDduduPort.java, src/main/java/com/ddudu/application/service/goal/DeleteGoalService.java, src/main/java/com/ddudu/infrastructure/persistence/adapter/RepeatDduduPersistenceAdapter.java, src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepositoryImpl.java, src/main/java/com/ddudu/infrastructure/persistence/repository/repeat_ddudu/RepeatDduduQueryRepository.java, src/main/java/com/ddudu/infrastructure/persistence/repository/repeat_ddudu/RepeatDduduQueryRepositoryImpl.java, src/main/java/com/ddudu/infrastructure/persistence/repository/repeat_ddudu/RepeatDduduRepository.java
=> fix: 목표 삭제 시 반복 뚜두가 남아있어 삭제가 되지 않는 오류 해결

src/main/java/com/ddudu/application/dto/stats/CompletionPerGoalDto.java, src/main/java/com/ddudu/application/dto/stats/response/MonthlyStatsResponse.java, src/main/java/com/ddudu/presentation/api/controller/StatsController.java, src/main/java/com/ddudu/presentation/api/doc/StatsControllerDoc.java
- #223 
- 의진님이 작성한 걸 그대로 활용하려다가 각 목표 별로 뚜두 생성 수의 순위를 매길 필요가 있어서 성격이 약간 다르더라고요
=> 월별 목표 뚜두 생성 통계

src/main/java/com/ddudu/application/port/in/repeat_ddudu/DeleteRepeatDduduUseCase.java, src/main/java/com/ddudu/application/port/out/repeat_ddudu/DeleteRepeatDduduPort.java, src/main/java/com/ddudu/application/service/repeat_ddudu/DeleteRepeatDduduService.java, src/main/java/com/ddudu/infrastructure/persistence/adapter/RepeatDduduPersistenceAdapter.java, src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepositoryImpl.java, src/main/java/com/ddudu/presentation/api/controller/RepeatDduduController.java, src/main/java/com/ddudu/presentation/api/doc/RepeatDduduControllerDoc.java, src/main/resources/db/data/afterMigrate.sql, src/test/java/com/ddudu/application/service/repeat_ddudu/DeleteRepeatDduduServiceTest.java, src/test/java/com/ddudu/fixture/DduduFixture.java, src/test/java/com/ddudu/fixture/RepeatDduduFixture.java
=> 반복 뚜두 삭제 기능 구현

.github/workflows/cd-dev.yaml, .github/workflows/cd-pipeline.yaml, .github/workflows/ci-pipeline.yaml, bootstrap/bootstrap-gateway/build.gradle.kts, common/src/main/java/com/ddudu/common/exception/ErrorCodeParser.java
- N/A
- 애플리케이션 진입점 모듈인 `bootstrap-gateway`에 예외 핸들러가 포함된 `bootstrap-common` 의존성 추가
- 기간 뚜두 예외 파싱 추가
- fix 브랜치 CI 활성화
=> fix: 예외 핸들러가 반영되지 않는 버그 수정

.github/workflows/cd-pipeline.yaml, application/user-application/src/test/java/com/ddudu/application/user/auth/service/SocialLoginServiceTest.java
- N/A
- github actions의 workflow_call에서 boolean input은 사실 boolean이 아닌 string임. 이를 사용하는 태스크 수정
- jwt에 시간이 포함되어 간헐적으로 검증 테스트 실패 수정
=> fix: github actions workflow inputs 타입 이슈 해결

.github/workflows/cd-pipeline.yaml
=> cd: typo 수정

.github/workflows/cd-pipeline.yaml
=> cd: workflow call input 수정

application/application-common/src/main/java/com/ddudu/application/common/dto/stats/SustenancePerGoal.java, application/application-common/src/main/java/com/ddudu/application/common/port/stats/in/CollectMonthlySustenanceUseCase.java, application/stats-application/src/main/java/com/ddudu/application/stats/service/CollectMonthlySustenanceService.java, application/stats-application/src/test/java/com/ddudu/application/stats/service/CollectMonthlySustenanceServiceTest.java, bootstrap/stats-api/src/main/java/com/ddudu/api/stats/controller/StatsController.java, bootstrap/stats-api/src/main/java/com/ddudu/api/stats/doc/StatsControllerDoc.java, domain/planning-domain/src/testFixtures/java/com/ddudu/fixture/DduduFixture.java
- Resolves #253 
- 월 목표 별 최대 지속 뚜두 통계 구현
=> Feat: 월 목표 별 최대 지속 뚜두 통계 구현

application/application-common/src/main/java/com/ddudu/application/common/dto/stats/PostponedPerGoal.java, application/application-common/src/main/java/com/ddudu/application/common/port/stats/in/CollectMonthlyPostponementUseCase.java, application/stats-application/src/main/java/com/ddudu/application/stats/service/CollectMonthlyPostponementService.java, application/stats-application/src/test/java/com/ddudu/application/stats/service/CollectMonthlyPostponementServiceTest.java, application/stats-application/src/test/java/com/ddudu/application/stats/service/CollectMonthlySustenanceServiceTest.java, bootstrap/stats-api/src/main/java/com/ddudu/api/stats/controller/StatsController.java, bootstrap/stats-api/src/main/java/com/ddudu/api/stats/doc/StatsControllerDoc.java, domain/planning-domain/src/testFixtures/java/com/ddudu/fixture/DduduFixture.java
- Resolves #255 
- 월 목표 별 미루기 통계 API 구현
=> Feat: 월 목표 별 미루기 통계 구현

application/application-common/src/main/java/com/ddudu/application/common/dto/notification/response/ReadNotificationInboxResponse.java, application/application-common/src/main/java/com/ddudu/application/common/port/notification/in/ReadNotificationInboxUseCase.java, application/application-common/src/main/java/com/ddudu/application/common/port/notification/out/NotificationInboxCommandPort.java, application/application-common/src/main/java/com/ddudu/application/common/port/notification/out/NotificationInboxLoaderPort.java, application/notification-application/src/main/java/com/ddudu/application/notification/inbox/ReadNotificationInboxService.java, application/notification-application/src/test/java/com/ddudu/application/notification/inbox/ReadNotificationInboxServiceTest.java, bootstrap/bootstrap-common/src/main/java/com/ddudu/bootstrap/common/doc/examples/NotificationInboxErrorExamples.java, bootstrap/notification-api/src/main/java/com/ddudu/api/notification/inbox/controller/NotificationInboxController.java, bootstrap/notification-api/src/main/java/com/ddudu/api/notification/inbox/doc/NotificationInboxControllerDoc.java, common/src/main/java/com/ddudu/common/exception/NotificationInboxErrorCode.java, domain/notification-domain/src/main/java/com/ddudu/domain/notification/event/aggregate/NotificationInbox.java, domain/notification-domain/src/test/java/com/ddudu/domain/notification/event/aggregate/NotificationInboxTest.java, infra/notification-infra-mysql/src/main/java/com/ddudu/infra/mysql/notification/inbox/adapter/NotificationInboxAdapter.java, infra/notification-infra-mysql/src/main/java/com/ddudu/infra/mysql/notification/inbox/entity/NotificationInboxEntity.java, infra/planning-infra-mysql/src/main/java/com/ddudu/infra/mysql/planning/ddudu/repository/DduduQueryRepository.java, infra/planning-infra-mysql/src/main/java/com/ddudu/infra/mysql/planning/ddudu/repository/DduduQueryRepositoryImpl.java
- Resolves #293 
- 알림 읽음 처리 도메인 로직 및 서비스 구현
=> Feat: 알림 읽음처리 구현
