DDu-Du-DDu-Du/back-end

build.gradle
scripts/local/Dockerfile
src/main/resources/application-local.yaml
src/test/resources/application.yaml

Resolves #4
* Dockerfile 이미지 빌드 시 MySQL 초기화 스크립트 제거
* flyway 의존성 추가 및 적용
* 기본적인 JPA 설정 `application.yaml`에 추가
* 로컬 및 테스트 환경에 `V1__schema.sql` 적용
* 로컬 환경에만 `resources/db/data/afterMigrate.sql` 적용
DB 모델이 어느 정도 완성될 때 까지는 `V1__schema.sql`에 추가하며 진행하고, schema에 새 테이블/속성 등이 추가될 때마다 도커 스크립트로 DB 재부팅 후 사용하면 될 것 같습니다

flyway를 사용해서 DB 마이그레이션 진행

---

src/main/java/com/ddudu/config/WebSecurityConfig.java

Resolves #17 
* api가 Spring Security에 걸리지 않기 위해 필요없는 필터들을 무시했습니다!
* `formLogin, rememberMe, logout, httpBasic, csrf`는 세션 기반 기능들이기 때문에 꺼놨습니다
* `requestCache` 또한 http 요청을 캐싱할 일이 없다고 생각해 꺼놨는데, 나중에 필요한 일이 생긴다면 그 때 지우겠습니다!

feat: api 요청 시 필요 없는 필터 무시

---

config/checkstyle/checkstyle.xml

Resolves #35 
- Checkstyle에서 연속적인 대문자를 최대 11개의 연속적인 대문자를 허용하도록 수정 완료했습니다. 
(혹시나 10개가 부족하다면 말씀해주세요! 더 늘리겠습니다.)

Checkstyle 연속적인 대문자 허용

---

src/main/java/com/ddudu/goal/controller/GoalController.java
src/main/java/com/ddudu/goal/domain/Color.java
src/main/java/com/ddudu/goal/domain/Goal.java
src/main/java/com/ddudu/goal/dto/requset/CreateGoalRequest.java
src/main/java/com/ddudu/goal/dto/response/CreateGoalResponse.java
src/main/java/com/ddudu/goal/dto/response/ErrorResponse.java
src/main/java/com/ddudu/goal/repository/GoalRepository.java
src/main/java/com/ddudu/goal/service/GoalService.java
src/test/java/com/ddudu/goal/controller/GoalControllerTest.java
src/test/java/com/ddudu/goal/domain/GoalTest.java
src/test/java/com/ddudu/goal/service/GoalServiceTest.java

Resolves #19
- [API 명세서](https://www.notion.so/backend-devcourse/005f1b84323d47cda1005197ddf112d4?pvs=4)
- user와 연관관계, `createdAt`, `updatedAt`은 추후 추가하겠습니다:)
- 생성만 했는데, 코드가 꽤 기네요ㅠㅜ (테스트 코드는 길지만, 내용이 비슷해서 빠르게 보실 수 있을 것 같습니당..)

목표 생성 기능 구현

---

src/main/java/com/ddudu/goal/controller/GoalController.java
src/main/java/com/ddudu/goal/domain/Goal.java
src/main/java/com/ddudu/goal/dto/requset/UpdateGoalRequest.java
src/main/java/com/ddudu/goal/dto/response/GoalResponse.java
src/main/java/com/ddudu/goal/service/GoalService.java
src/main/resources/db/data/afterMigrate.sql
src/test/java/com/ddudu/goal/controller/GoalControllerTest.java
src/test/java/com/ddudu/goal/domain/GoalTest.java
src/test/java/com/ddudu/goal/service/GoalServiceTest.java

Resolves #41
- 목표 수정 요청, 응답 DTO 생성
- 목표 수정 컨트롤러 작성 (PUT /api/goals/{id})
- Goal 엔티티에 applyGoalUpdates() 메서드 생성
- 목표 수정 서비스 구현
- 테스트 코드 작성

목표 수정 기능 구현

---

src/main/java/com/ddudu/goal/controller/GoalController.java
src/main/java/com/ddudu/goal/domain/Goal.java
src/main/java/com/ddudu/goal/dto/response/GoalResponse.java
src/main/java/com/ddudu/goal/dto/response/GoalSummaryDTO.java
src/main/java/com/ddudu/goal/dto/response/GoalSummaryResponse.java
src/main/java/com/ddudu/goal/repository/GoalRepository.java
src/main/java/com/ddudu/goal/service/GoalService.java
src/main/resources/db/data/afterMigrate.sql
src/main/resources/db/migration/V1__schema.sql
src/test/java/com/ddudu/goal/controller/GoalControllerTest.java
src/test/java/com/ddudu/goal/domain/GoalTest.java
src/test/java/com/ddudu/goal/service/GoalServiceTest.java
src/test/java/com/ddudu/todo/domain/TodoTest.java
src/test/java/com/ddudu/todo/service/TodoServiceTest.java

Resolves #39 
- Goal / User 다대일 연관 관계 매핑
- 전체 조회 시 목표 상태, 생성일 기준으로 정렬을 하기 위해 JPQL 사용
- 연관 관계 매핑에 따른 기존 테스트 코드 변경 및 Faker 도입
❗참고
- 로그인 구현 이전이기 때문에 임시로 userId를 QueryParam으로 입력 받습니다! (추후 변경 예정)

목표 조회(단일, 전체) 기능 구현

---

src/main/java/com/ddudu/common/BaseEntity.java
src/main/java/com/ddudu/goal/controller/GoalController.java
src/main/java/com/ddudu/goal/domain/Goal.java
src/main/java/com/ddudu/goal/repository/GoalRepository.java
src/main/java/com/ddudu/goal/repository/GoalRepositoryCustom.java
src/main/java/com/ddudu/goal/repository/GoalRepositoryImpl.java
src/main/java/com/ddudu/goal/service/GoalService.java
src/main/java/com/ddudu/todo/domain/Todo.java
src/main/java/com/ddudu/user/domain/User.java
src/main/java/com/ddudu/user/dto/request/SignUpRequest.java
src/test/java/com/ddudu/goal/controller/GoalControllerTest.java
src/test/java/com/ddudu/goal/domain/GoalTest.java
src/test/java/com/ddudu/goal/service/GoalServiceTest.java
src/test/java/com/ddudu/user/controller/UserControllerTest.java

Resolves #57
- GoalService에서 목표 조회 기능에 `getById()`, `getAllById()` 네이밍을 붙이다가 생각한 건데, update(), delete()도 `updateById()`, `deleteById()`로 네이밍을 바꿀까요? 
- GoalRepository에 `findById()`, `findAllByUser()`를 JPQL로 구현을 했는데요! SpringDataJpa를 사용하면 JPQL을 사용할 필요없이 
```
Optional<Goal> findByIdAndIsDeletedIsFalse(Long id);
``` 
처럼 사용할 수 있더라구요! 그런데 메서드명이 너무 길어져서 저는 JPQL을 사용했는데, 어떤 방식이 나을까요?
- Delete를 하고 현재 NoContent를 반환하는데요! OK를 반환하고 body에 삭제된 리소스의 아이디를 보내는 것이 더 나을까요?

목표 삭제 기능 구현

---

src/main/java/com/ddudu/auth/exception/AuthErrorCode.java
src/main/java/com/ddudu/common/annotation/Login.java
src/main/java/com/ddudu/common/annotation/LoginUserArgumentResolver.java
src/main/java/com/ddudu/config/WebConfig.java
src/main/java/com/ddudu/user/controller/UserController.java

Resolves #71 
로그인한 유저 정보가 필요할 때마다 Authentication을 인자로 받아 
```java
long userId = ((JwtAuthToken) authentication).getUserId();
```
를 하는 것이 조금  번거롭고, 해당 로직이 여러 컨트롤러에서 중복이 될 것 같더라구요!
그래서 컨트롤러 메서드의 파라미터 앞에 `@Login long loginId` 를 하면, 바로 로그인 유저 아이디를 쓸 수 있도록 하고 싶어 
`LoginUserArgumentResolver`를 구현했습니다!
**Done**
- `@Login` 애너테이션 생성
- `LoginUserArgumentResolver ` 생성
- `LoginUserArgumentResolver` 등록
- `LoginUserArgumentResolver` 도입

@Login 애너테이션 구현

---

src/main/java/com/ddudu/common/exception/ForbiddenException.java
src/main/java/com/ddudu/common/exception/GeneralExceptionHandler.java
src/main/java/com/ddudu/todo/controller/TodoController.java
src/main/java/com/ddudu/todo/exception/TodoErrorCode.java
src/main/java/com/ddudu/todo/service/TodoService.java
src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
src/test/java/com/ddudu/todo/service/TodoServiceTest.java

Resolves #77 
- 로그인한 유저가 자신의 할 일만 삭제할 수 있도록, 서비스 로직에 검증을 추가했습니다!
- 만약 할 일의 유저와 로그인 유저가 다를 경우 `ForbiddenException(TodoErrorCode.INVALID_AUTHORITY)` 예외를 던집니다!

할 일 삭제 기능 구현

---

src/main/java/com/ddudu/user/controller/UserController.java
src/main/java/com/ddudu/user/domain/User.java
src/main/java/com/ddudu/user/dto/request/UpdateEmailRequest.java
src/main/java/com/ddudu/user/dto/request/UpdatePasswordRequest.java
src/main/java/com/ddudu/user/dto/response/UpdatePasswordResponse.java
src/main/java/com/ddudu/user/exception/UserErrorCode.java
src/main/java/com/ddudu/user/service/UserService.java
src/test/java/com/ddudu/user/controller/UserControllerTest.java
src/test/java/com/ddudu/user/service/UserServiceTest.java

Resolves #45 
* 이메일 변경 시, 변경 전 이메일과 변경할 이메일이 동일하거나 변경할 이메일이 중복되면 이메일 변경에 실패합니다.
* 비밀번호 변경 시, 변경 전 비밀번호와 변경할 비밀번호가 동일하면 비밀번호 변경에 실패합니다.

이메일 및 비밀번호 변경 기능 구현

---

src/main/java/com/ddudu/common/BaseEntity.java
src/main/java/com/ddudu/like/controller/LikeController.java
src/main/java/com/ddudu/like/domain/Like.java
src/main/java/com/ddudu/like/dto/request/LikeRequest.java
src/main/java/com/ddudu/like/dto/response/LikeResponse.java
src/main/java/com/ddudu/like/exception/LikeErrorCode.java
src/main/java/com/ddudu/like/repository/LikeRepository.java
src/main/java/com/ddudu/like/repository/LikeRepositoryCustom.java
src/main/java/com/ddudu/like/repository/LikeRepositoryImpl.java
src/main/java/com/ddudu/like/service/LikeService.java
src/main/java/com/ddudu/todo/dto/response/LikeInfo.java
src/main/java/com/ddudu/todo/dto/response/TodoInfo.java
src/main/java/com/ddudu/todo/service/TodoService.java
src/main/resources/db/data/afterMigrate.sql
src/main/resources/db/migration/V1__schema.sql
src/test/java/com/ddudu/like/controller/LikeControllerTest.java
src/test/java/com/ddudu/like/domain/LikeTest.java
src/test/java/com/ddudu/like/service/LikeServiceTest.java
src/test/java/com/ddudu/todo/service/TodoServiceTest.java

Resolves #82
Resolves #94 
* 좋아요 기능 구현
* 좋아요 취소 기능 구현
* 좋아요 단일 조회 기능 구현
- todomate 앱을 보니까 **단일 조회**의 경우 꼭 좋아요를 한 사용자만 조회할 수 있는 것이 아니고 모든 사용자가 좋아요를 조회할 수 있기에, `@Login`을 따로 추가하지 않았습니다. 그래도 추후 확장성을 위해 @Login을 추가하는 것이 좋을까요?
- 기존에 구현된 기능과 비슷하기에 한 번에 PR을 날렸는데 양이 생각보다 많네요.. 😢

할 일 좋아요 관련 기능 구현

---

src/main/java/com/ddudu/user/domain/Following.java
src/main/java/com/ddudu/user/exception/FollowingErrorCode.java
src/main/java/com/ddudu/user/service/FollowingService.java
src/test/java/com/ddudu/user/controller/UserControllerTest.java
src/test/java/com/ddudu/user/service/FollowingServiceTest.java

* Resolves #112 
* 팔로잉 상태 수정 시 요청 받은 사용자인지 확인
* 팔로잉 삭제 시 로그인 사용자가 존재하는지 확인
* 해당 서비스 테스트 수정

팔로잉 요청 받은 사용자가 수락/무시 할 수 없던 버그 수정

---

src/main/java/com/ddudu/user/controller/UserController.java
src/main/java/com/ddudu/user/dto/FollowingSearchType.java
src/main/java/com/ddudu/user/repository/UserRepositoryCustom.java
src/main/java/com/ddudu/user/repository/UserRepositoryImpl.java
src/main/java/com/ddudu/user/service/UserService.java
src/test/java/com/ddudu/auth/service/AuthServiceTest.java
src/test/java/com/ddudu/user/controller/UserControllerTest.java
src/test/java/com/ddudu/user/service/UserServiceTest.java

* Resolves #98 
* GET /api/users/{id}/followings
* search type에 따른 로그인 사용자의 follower/followee 조회
* ParameterizedTest로 두 케이스 모두 테스트

팔로워 조회 기능 구현

---

.aws/dev-task-definition.json

* Resolves #124 
* `/.github/workflows`에 있는 actions 파이프라인
* `/.aws`에 있는 task definition을 봐주십쇼
**ECS with EC2**
1. github actions에서 **빌드** (테스트 제외)
2. 빌드된 **jar파일**을 **도커 이미지**로 빌드
3. 빌드된 이미지를 AWS **Private Elastic Container Registry**(ECR)에 저장 (500MB짜리 이미지까지 무료)
4. 미리 작성된 task definition에 빌드된 **이미지 주소 삽입**
- aws에서 컨테이너를 실행시킬 ECS가 존재, ECS는 등록된 Task Definition을 바탕으로 컨테이너 실행
5. 이미지까지 삽입돼서 작성된 task definition으로 **ecs 태스크 실행**
**배포 시 AWS에서 일어나고 있는 일들**
1. 1개의 EC2(t2.micro)에서 리소스 풀로 컨테이너 구동
2. 배포 파이프라인을 거쳐 ECS에 태스크 생성
3. **Auto Scaling Group**이 EC2 인스턴스 **1개 추가 생성**
4. 생성된 EC2 인스턴스를 태스크 돌릴 수 있는 **ECS 컨테이너 인스턴스**로 등록
5. 가용할 수 있는 컨테이너 인스턴스가 생기면 바로 **추가된 태스크 실행**
6. 성공 시 돌아가는 태스크는 두개 (기존 + 추가 배포)
7. 돌아가는 EC2 인스턴스도 두개 (기존 태스크 + 추가 배포 태스크)
8. 목표 태스크는 1개이니 1개가 불필요해짐 -> **기존 태스크 종료**
9. 용량 공급자의 …

CD 파이프라인 작성

---

src/main/java/com/ddudu/application/domain/ddudu/domain/Ddudu.java
src/main/java/com/ddudu/application/domain/ddudu/exception/DduduErrorCode.java
src/main/java/com/ddudu/application/port/in/ddudu/RepeatUseCase.java
src/main/java/com/ddudu/application/port/out/ddudu/RepeatDduduPort.java
src/main/java/com/ddudu/application/service/ddudu/RepeatService.java
src/main/java/com/ddudu/infrastructure/persistence/adapter/DduduPersistenceAdapter.java
src/main/java/com/ddudu/infrastructure/persistence/entity/DduduEntity.java
src/main/java/com/ddudu/presentation/api/controller/DduduController.java
src/main/java/com/ddudu/presentation/api/doc/DduduControllerDoc.java
src/test/java/com/ddudu/application/domain/ddudu/domain/DduduTest.java
src/test/java/com/ddudu/application/service/ddudu/RepeatServiceTest.java

* Resolves #159 
* 뚜두 다른 날 반복하기 서비스 구현
* API 구현 및 문서 수정
* Outgoing 포트를 해당 유스케이스 용으로 이렇게 한 번 해봤습니다. 보시고 코멘트 주세요!!
* 유스케이스 별 통합테스트는 참 유용한 것 같습니다.

뚜두 다른 날 반복하기 (다시하기) 구현

---

src/main/java/com/ddudu/application/dto/ddudu/DduduCursorDto.java
src/main/java/com/ddudu/application/dto/ddudu/request/DduduSearchRequest.java
src/main/java/com/ddudu/application/dto/scroll/OrderType.java
src/main/java/com/ddudu/application/dto/scroll/request/ScrollRequest.java
src/main/java/com/ddudu/application/port/in/ddudu/DduduSearchUseCase.java
src/main/java/com/ddudu/application/port/out/ddudu/DduduSearchPort.java
src/main/java/com/ddudu/application/port/out/ddudu/SaveDduduPort.java
src/main/java/com/ddudu/application/port/out/user/UserLoaderPort.java
src/main/java/com/ddudu/application/service/ddudu/DduduSearchService.java
src/main/java/com/ddudu/infrastructure/persistence/adapter/DduduPersistenceAdapter.java
src/main/java/com/ddudu/infrastructure/persistence/adapter/UserPersistenceAdapter.java
src/main/java/com/ddudu/infrastructure/persistence/dto/DduduCursorDto.java
src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepository.java
src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepositoryImpl.java
src/main/java/com/ddudu/presentation/api/controller/DduduController.java
src/main/java/com/ddudu/presentation/api/doc/DduduControllerDoc.java
src/test/java/com/ddudu/application/service/ddudu/DduduSearchServiceTest.java
src/test/java/com/ddudu/fixture/DduduFixture.java

* Resolves #166 
* 뚜두 목록 조회 무한 스크롤 구현
* 아직까진 본인의 뚜두만 조회할 수 있도록 구현했습니다
* 약간 보시기 힘들 수도 있는데 쿼리가 핵심이고 persistence에서는 크게 두 부분으로 나눌 수 있습니다
* select query 수행
* 커서 확인: 최신순 - id / 필터 종류별 커서 추가 가능
* 공개여부 확인: 본인 - 전부 / 팔로워 - 팔로워 + 퍼블릭 / 이외 - 퍼블릭
* 조건 설정: 커서 + 공개여부 + 조회 대상 사용자 아이디
* 쿼리: 조회 사이즈 + 1개만큼
* 쿼리 결과 DTO 매핑
* 스크롤 응답: `isEmpty`, `contents`, `nextCursor`
* 다음 커서: `쿼리 결과 사이즈 > 조회 요청 사이즈`일 시 다음 컨텐츠 존재 -> `다음 커서 = 현재 마지막 아이템의 커서` -> 다음 조회 시 커서 의 다음 아이템부터 조회
* 사용자 개별조회를 추가했는데 지금 생각해보니 겹치네요. 나중에 지우겠습니다!
* 테스트 시 saveAll이 필요해서 추가했습니다. 계속 생각하는건데 유스케이스 별 인터페이스 하나만 확장하는게 엔티티가 엮이면 어렵고, 어댑터를 아예 통짜로 하나만 가져가기도 힘들고, 어댑터를 유스케이스 별로 만들기도 너무 복잡하고 중복이 많을 것 같고, 포트를 Repository처럼 엔티티 별로 만들고 어댑터를 그냥 JPARepository의 확장 느낌으로 도메인으로 변환만 해줘야 하나 싶기도 하고..어렵네요ㅠㅠ 좀 더 고민해보겠습니다
* 헷갈리시면 슬랙 바로 주셔도 좋습니다!!

뚜두 목록 조회 구현

---

src/main/java/com/ddudu/application/domain/repeat_ddudu/domain/MonthlyRepeatPattern.java
src/main/java/com/ddudu/application/domain/repeat_ddudu/domain/RepeatDdudu.java
src/main/java/com/ddudu/application/domain/repeat_ddudu/domain/RepeatPattern.java
src/main/java/com/ddudu/application/domain/repeat_ddudu/domain/WeeklyRepeatPattern.java
src/main/java/com/ddudu/application/domain/repeat_ddudu/exception/RepeatDduduErrorCode.java
src/main/java/com/ddudu/application/domain/repeat_ddudu/service/RepeatDduduDomainService.java
src/main/java/com/ddudu/application/port/out/ddudu/DduduLoaderPort.java
src/main/java/com/ddudu/application/port/out/repeat_ddudu/RepeatDduduLoaderPort.java
src/main/java/com/ddudu/application/service/repeat_ddudu/CreateRepeatDduduService.java
src/main/java/com/ddudu/infrastructure/persistence/adapter/DduduPersistenceAdapter.java
src/main/java/com/ddudu/infrastructure/persistence/adapter/RepeatDduduPersistenceAdapter.java
src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduRepository.java
src/test/java/com/ddudu/application/domain/repeat_ddudu/domain/RepeatDduduTest.java
src/test/java/com/ddudu/application/domain/repeat_ddudu/service/RepeatDduduDomainServiceTest.java
src/test/java/com/ddudu/application/service/repeat_ddudu/CreateRepeatDduduServiceTest.java
src/test/java/com/ddudu/fixture/RepeatDduduFixture.java

Closes #191 
- 기존 코드 리팩토링
- 테스트 코드 작성
- `RepeatDdudu` 도메인 생성 및 테스트를 먼저 PR로 올렸어야 했는데, 생성 기능이랑 같이 작업하니 PR 단위가 너무 커졌습니다.. 죄송합니다😭
- 반복 날짜 확인에 대한 테스트 코드가 깔끔하지 못한 것 같은데.. 죄송합니다.. 조금 더 고민해서 리팩토링 때 가독성있게 수정하겠습니다..!!

반복 뚜두 생성 테스트 코드 작성

---

src/main/java/com/ddudu/application/domain/repeat_ddudu/util/DayOfWeekUtil.java
src/main/java/com/ddudu/application/dto/ddudu/response/DduduCompletionResponse.java
src/main/java/com/ddudu/application/port/in/ddudu/CalculateWeeklyCompletionUseCase.java
src/main/java/com/ddudu/application/port/out/ddudu/DduduStatsPort.java
src/main/java/com/ddudu/application/service/ddudu/CalculateWeeklyCompletionService.java
src/main/java/com/ddudu/infrastructure/persistence/adapter/DduduPersistenceAdapter.java
src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepository.java
src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepositoryImpl.java
src/main/java/com/ddudu/old/persistence/repository/TodoRepositoryImpl.java
src/main/java/com/ddudu/old/todo/domain/OldTodoRepository.java
src/main/java/com/ddudu/old/todo/service/TodoService.java
src/main/java/com/ddudu/presentation/api/controller/DduduController.java
src/main/java/com/ddudu/presentation/api/doc/DduduControllerDoc.java
src/test/java/com/ddudu/application/service/ddudu/CalculateWeeklyCompletionServiceTest.java
src/test/java/com/ddudu/old/todo/service/DduduServiceTest.java

Resolves #206 
일단, 기존 코드(old) 부분만 마이그레이션 해봤습니다! 
(프론트에서 메인 페이지 작업 중이라 일단 API 열고, 추후 리팩토링해도 될 것 같아서요!)
- 기존 Querydsl로 날아가던 쿼리 거의 유사하게 썼습니다! 
- 데이터 타입 변경 `LocalDateTime(start_at)` → `LocalDate (scheduled_on)`
- join이 where절 보다 먼저 실행되서, join 부분에서 먼저 거를 수 있는 부분은 거를 수 있도록 변경했습니다! (userId 확인 / 목표 타입 확인)
- 아래와 같은 식으로 쿼리 날아갑니당~

주간 뚜두 완료도 조회

---

src/main/java/com/ddudu/application/domain/ddudu/domain/Ddudu.java
src/main/java/com/ddudu/application/domain/ddudu/domain/DduduList.java
src/main/java/com/ddudu/application/domain/ddudu/domain/Timetable.java
src/main/java/com/ddudu/application/domain/goal/domain/enums/PrivacyType.java
src/main/java/com/ddudu/application/domain/user/domain/enums/Relationship.java
src/main/java/com/ddudu/application/dto/ddudu/BasicDduduWithGoalIdAndTime.java
src/main/java/com/ddudu/application/dto/ddudu/TimeGroupedDdudus.java
src/main/java/com/ddudu/application/port/out/ddudu/DduduLoaderPort.java
src/main/java/com/ddudu/application/port/out/goal/GoalLoaderPort.java
src/main/java/com/ddudu/application/service/ddudu/GetDailyDdudusByGoalService.java
src/main/java/com/ddudu/application/service/ddudu/GetTimetableService.java
src/main/java/com/ddudu/application/service/goal/RetrieveAllGoalsService.java
src/main/java/com/ddudu/infrastructure/persistence/adapter/DduduPersistenceAdapter.java
src/main/java/com/ddudu/infrastructure/persistence/adapter/GoalPersistenceAdapter.java
src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepository.java
src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepositoryImpl.java
src/test/java/com/ddudu/application/service/auth/SocialLoginServiceTest.java
src/test/java/com/ddudu/application/service/ddudu/GetDailyDdudusByTimeServiceTest.java

Resolves #213 
- 타임테이블 응답 시 `beginAt`과 `endAt`도 함께 응답하도록 변경 
- 유저 사이 관계를 확인하기 위한 `Relationship` enum 추가
- Persistence 레이어에서 처리하는 비즈니스 로직을 비즈니스 레이어로 이동
- `Timetable`, `DduduList` 컬렉션 객체 생성
저번에 이야기 나눴던 [DB 연산 vs 애플리케이션에서 처리](https://velog.io/@uijin/DB-%EC%A7%91%EA%B3%84%EC%97%B0%EC%82%B0-vs-%EC%95%A0%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98%EC%97%90%EC%84%9C-%EC%B2%98%EB%A6%AC)에 대해 고민해 봤는데, 
Persistence 레이어에서는 데이터를 필터링/최소화해서 가져오는 것에만 집중하고,
애플리케이션에서 비즈니스 로직을 처리해야 추후 비즈니스 로직 변경에 대한 유연성도 늘어나고, 쿼리에 대한 재사용성도 늘어날 것 같더라구요! 
그래서 일단, 지금 PR 올린 부분만 수정을 해봤습니다:)
그리고 계속 이야기했던, `User` 사이 관계와 `PrivacyType`은 Relationship이라는 enum을 만들어봤는데요! 일단 로직이 Relationship 안에 있긴 하지만, 나중에 팔로우 기능이 구현되면 DB에 접근해야 Relationship을 알 수 있어서.. `UserRelationshipService` 또는 `UserRelationshipFacade` 를 만들거나 해야 될 것 같아요!

타임 테이블 뚜두 데이터 포맷 변경

---

src/main/java/com/ddudu/application/dto/ddudu/BasicDduduWithGoalIdAndTime.java
src/main/java/com/ddudu/application/port/in/ddudu/CalculateCompletionUseCase.java
src/main/java/com/ddudu/application/service/ddudu/CalculateCompletionService.java
src/main/java/com/ddudu/presentation/api/controller/DduduController.java
src/main/java/com/ddudu/presentation/api/doc/DduduControllerDoc.java
src/test/java/com/ddudu/application/service/ddudu/CalculateCompletionServiceTest.java

Resolves #212 
주별 완료도 조회와 겹치는 부분이 많아서, 그냥 **주별 완료도 조회 서비스를 특정 구간사이의 완료도 조회로 변경해서 범용적으로 사용**했습니다! 
그래서 서비스 로직은 똑같고, 대신 파라미터 초기화하는 부분을 컨트롤러로 이동했습니다!😉 (컨트롤러에서 서비스 호출을 위해 파라미터를 정제하거나 기본값을 주는 건 괜찮다고 생각했는데, 괜찮을까요?)
전에 이야기 나눴던 것처럼, 요부분 인재님이 작업 하시고 있는 걸로 아는데 일단 PR 올리고 추후 리팩토링 하면 좋을 것 같습니다!
+) 타임테이블 조회 시 데이터 포맷이 잘못 올라가서.. 요 PR에 조심스레 같이 올려봅니다ㅎㅎ..

월별 뚜두 완료도 조회

---

src/main/java/com/ddudu/application/domain/repeat_ddudu/domain/RepeatDdudu.java
src/main/java/com/ddudu/application/domain/repeat_ddudu/exception/RepeatDduduErrorCode.java
src/main/java/com/ddudu/application/domain/repeat_ddudu/service/RepeatDduduDomainService.java
src/main/java/com/ddudu/application/dto/goal/request/ChangeGoalStatusRequest.java
src/main/java/com/ddudu/application/dto/repeat_ddudu/request/UpdateRepeatDduduRequest.java
src/main/java/com/ddudu/application/port/in/repeat_ddudu/UpdateRepeatDduduUseCase.java
src/main/java/com/ddudu/application/port/out/ddudu/DeleteDduduPort.java
src/main/java/com/ddudu/application/port/out/repeat_ddudu/RepeatDduduLoaderPort.java
src/main/java/com/ddudu/application/port/out/repeat_ddudu/UpdateRepeatDduduPort.java
src/main/java/com/ddudu/application/service/repeat_ddudu/UpdateRepeatDduduService.java
src/main/java/com/ddudu/infrastructure/persistence/adapter/DduduPersistenceAdapter.java
src/main/java/com/ddudu/infrastructure/persistence/adapter/RepeatDduduPersistenceAdapter.java
src/main/java/com/ddudu/infrastructure/persistence/entity/RepeatDduduEntity.java
src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepository.java
src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepositoryImpl.java
src/main/java/com/ddudu/presentation/api/controller/RepeatDduduController.java
src/main/java/com/ddudu/presentation/api/doc/RepeatDduduControllerDoc.java
src/main/java/com/ddudu/presentation/api/doc/error/RepeatDduduErrorExamples.java
src/test/java/com/ddudu/application/service/repeat_ddudu/UpdateRepeatDduduServiceTest.java

Resolves #200 
- 반복 뚜두 수정 시, 해당 반복 뚜두와 연관된 뚜두는 기본적으로 **삭제** 후 변경된 내용에 맞게 다시 연관된 뚜두들을 생성 (오늘 이후부터)
❗️ 만약, 이미 완료한 뚜두라면 그대로 둠
- 반복 패턴이 변경되는 것이 아니라면 굳이 관련 뚜두들을 삭제 후 생성할 필요없이, 벌크 업데이트 가능!

반복 뚜두 수정 기능 구현

---

src/main/java/com/ddudu/application/domain/repeat_ddudu/service/RepeatDduduDomainService.java
src/main/java/com/ddudu/application/dto/goal/request/CreateGoalRequest.java
src/main/java/com/ddudu/application/dto/goal/request/CreateRepeatDduduRequestWithoutGoal.java
src/main/java/com/ddudu/application/dto/repeat_ddudu/RepeatPatternDto.java
src/main/java/com/ddudu/application/service/goal/CreateGoalService.java
src/test/java/com/ddudu/application/domain/goal/service/GoalDomainServiceTest.java
src/test/java/com/ddudu/application/service/goal/CreateGoalServiceTest.java

Resolves #198 
- 반복 뚜두 생성을 위해 `CreateGoalService`가  `CreateRepeatDduduService` 의 메서드를 호출하도록 구현했습니다.
- Service 간 의존성을 퍼사드 패턴으로 해결
- 목표 생성 후 반복 뚜두 생성을 비동기로 변경

목표 생성 시 반복  뚜두도 함께 생성할 수 있도록 변경

---

src/main/java/com/ddudu/application/domain/ddudu/domain/Timetable.java
src/main/java/com/ddudu/application/dto/ddudu/DduduForTimetable.java
src/main/java/com/ddudu/application/dto/ddudu/TimeGroupedDdudus.java
src/main/java/com/ddudu/application/dto/goal/response/GoalWithRepeatDduduResponse.java
src/main/java/com/ddudu/application/dto/repeat_ddudu/RepeatDduduDto.java
src/main/java/com/ddudu/application/service/ddudu/GetTimetableService.java
src/test/java/com/ddudu/application/service/ddudu/GetDailyDdudusByTimeServiceTest.java
src/test/java/com/ddudu/application/service/goal/RetrieveGoalServiceTest.java

Resolves #240 
- 타임테이블 조회 시 ddudus 하위에 color 컬럼 추가
- 목표 상세 조회 시 반복 뚜두에 beginAt, endAt 추가

feat: 응답 데이터 형식 변경 (타임테이블 API, 목표 상세 조회 API)

---

application/application-common/src/main/java/com/ddudu/application/common/dto/stats/AchievementPerGoal.java
application/application-common/src/main/java/com/ddudu/application/common/dto/stats/CreationCountPerGoalDto.java
application/application-common/src/main/java/com/ddudu/application/common/port/stats/in/CollectMonthlyAchievementUseCase.java
application/stats-application/src/main/java/com/ddudu/application/stats/service/CollectMonthlyAchievementService.java
application/stats-application/src/main/java/com/ddudu/application/stats/service/CollectMonthlyCreationStatsService.java
application/stats-application/src/test/java/com/ddudu/application/stats/service/CollectMonthlyAchievementServiceTest.java
application/stats-application/src/test/java/com/ddudu/application/stats/service/CollectMonthlyStatsSummaryTest.java
bootstrap/bootstrap-common/src/main/java/com/ddudu/bootstrap/common/doc/examples/StatsErrorExamples.java
bootstrap/stats-api/src/main/java/com/ddudu/api/stats/controller/StatsController.java
bootstrap/stats-api/src/main/java/com/ddudu/api/stats/doc/StatsControllerDoc.java
common/src/main/java/com/ddudu/common/exception/StatsErrorCode.java
domain/stats-domain/src/main/java/com/ddudu/aggregate/BaseStats.java
domain/stats-domain/src/main/java/com/ddudu/aggregate/MonthlyStats.java
domain/stats-domain/src/test/java/com/ddudu/aggregate/MonthlyStatsTest.java
domain/stats-domain/src/testFixtures/java/com/ddudu/fixtures/BaseStatsFixture.java
infra/planning-infra-mysql/src/main/java/com/ddudu/infra/mysql/planning/ddudu/repository/DduduQueryRepositoryImpl.java

- Resolves #182 
- 월 목표 별 달성률 통계 구현
- 기본 통계 정보에 목표명 추가
- 월 통계 도메인에 목표 별 그룹핑 추가
- 목표 별 그룹핑된 월 통계에서 공통 정보(목표아이디, 목표명) 사용 시 검증 추가
- 뚜두 생성 수 통계에 해당 변경 사항 반영

Feat: 월 목표 별 달성률 통계 구현

---

application/planning-application/src/test/java/com/ddudu/application/planning/ddudu/service/CancelReminderServiceTest.java
application/planning-application/src/test/java/com/ddudu/application/planning/ddudu/service/ChangeNameServiceTest.java
application/planning-application/src/test/java/com/ddudu/application/planning/ddudu/service/DeleteDduduServiceTest.java
application/planning-application/src/test/java/com/ddudu/application/planning/ddudu/service/RetrieveDduduServiceTest.java
application/planning-application/src/test/java/com/ddudu/application/planning/ddudu/service/SetReminderServiceTest.java
application/planning-application/src/test/java/com/ddudu/application/planning/ddudu/service/SwitchStatusServiceTest.java
bootstrap/bootstrap-common/src/main/java/com/ddudu/bootstrap/common/exception/GlobalExceptionHandler.java
bootstrap/planning-api/src/main/java/com/ddudu/api/planning/ddudu/doc/DduduControllerDoc.java
domain/planning-domain/src/main/java/com/ddudu/domain/planning/ddudu/aggregate/Ddudu.java
domain/planning-domain/src/test/java/com/ddudu/domain/planning/ddudu/aggregate/DduduTest.java

- Resolves #270 
- 권한 없음은 SecurityException 예외 발생
- GlobalExceptionHandler에 SecurityException 핸들링 추가
- 누락 문서 예외 추가

Fix: Forbidden 예외 발생 수정
